spring:
  application:
    name: wendys-rennpferde
server:
    port: 8080
custom:
  db:
    url: "jdbc:h2:~/sepm1;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"
    user: "sa"
    password: ""
    driver: "org.h2.Driver"

---
# YOU MUST NOT CHANGE THE TEST PROFILE
spring:
  profiles: test
custom:
  db:
    url: "jdbc:h2:mem:;INIT=RUNSCRIPT FROM 'classpath:sql/createSchema.sql'"